### ISSUE TITLE
nipals::predict.nipals

### ISSUE THREAD

**Issue by lgatto** [kwstat/nipals#1]
Thank you very much for the package - it does exactly what is on the tin!

Would it be possible or would you consider implementing a `predict.nipals` function along the lines of `stats:::predict.prcomp` function?

**Comment by kwstat** [comment]
Semi-fix via https://github.com/kwstat/nipals/commit/e7494cd8738f87bdfb3b79d095eb589bd1eb77d3

The `nipals()` function now includes `center` and `scale` in the returned object, so you can get predictions by adding a `princomp` class to the model object. Here's an example:

```
  set.seed(42)
  ix <- sample(nrow(iris), nrow(iris)*0.75)
  iris.train <- iris[ix,1:4]
  iris.test <- iris[-ix,1:4]
  
  # Method 1: Assign a class to the nipals model
  m1 <- nipals(iris.train[,1:4])
  class(m1) <- "princomp"
  predict(m1, newdata=iris.test[,1:4])

```
