### ISSUE TITLE
error when using one component

### ISSUE THREAD

**Issue by Jimi-o-Jimi** [kwstat/nipals#2]
Thank you very much for the package! 
I ran into a little error when calculating the fitted x while setting `ncomp = 1`. 
I think the problem is, if there is only a single eigenvalue, `diag(eig)` leads to an eig×eig identity matrix. 

`xhat <- tcrossprod(tcrossprod(scores, diag(eig)), loadings)`

I encountered this issue trying to implement Wold's cross-validation for PCA, where components get added one after the other, with some steps between each. Easily fixed for my purposes, but thought you might like to know.

**Comment by kwstat** [comment]
Good catch. Fixed via https://github.com/kwstat/nipals/commit/10b9644d9e2e708cb5885e31598911799bd218c4
